---
- hosts: master
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get the latest stable version
      shell: lsb_release -cs
      register: stable_version

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ stable_version.stdout_lines[0] }} stable
        state: present

    - name: Install docker and its dependecies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - docker status

    - name: Add "{{ ansible_user }}" current user to docker group
      user:
        name: "{{ ansible_user}}"
        group: docker

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent 
        src: none 
      with_items:
          - swap
          - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl
    
    #- name: Get the host part of the IP 
      #shell: host {{ ansible_fqdn }} | awk '{print $4}' 
      #register: node_ip
    #  setup:
    #    node_ip: "{{ ansible_eth1.ipv4.address }}"      

    - name: Creates Kubelet directory
      file:
        path: /etc/default/kubelet
        state: touch 

    - name: Configure node ip
      lineinfile:
        name: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_eth1.ipv4.address }}

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted

#    - name: Reset Cluster
#      command: kubeadm reset -f

#    - name: Remove previous Cluster config
#      file:
#        path: /home/{{ ansible_user }}/.kube 
#        state: absent

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address {{ ansible_eth1.ipv4.address }} --node-name k8s-master --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=All

    - name: Create kubeconfig directory for running user
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        mode: '0755'

    - name: Copy kubeconfig for running user
      command: cp -i /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
  
    - name: Change ownership kubeconfig for running user
      file:
        path: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      
    - name: Install flannel pod network
      become: false
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    - name: Generate join command
      become: false
      command: kubeadm token create --print-join-command
      register: join_command
      ignore_errors: True

    - name: Copy join command to local file
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  handlers:
    - name: docker status
      service: name=docker state=started
