apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: worker-1
      image:
      command:
      volumeMounts:
        - mountPath: "/mnt"
          name: task-pv-storage
  nodeName: